
import { MutualFund, FundCategory, RiskLevel } from './types';

export const MOCK_FUNDS: MutualFund[] = [
  {
    id: 1,
    name: "Parag Parikh Flexi Cap Fund",
    category: FundCategory.Equity,
    riskLevel: RiskLevel.VeryHigh,
    returns: { '1yr': 38.5, '3yr': 20.8, '5yr': 23.9 },
    aum: 66400,
    expenseRatio: 0.62,
    fundManager: "Rajeev Thakkar",
    description: "An open-ended dynamic equity scheme investing across large cap, mid cap, small cap stocks. Known for its value-oriented investment strategy and significant holdings in international equities.",
    topHoldings: ["HDFC Bank", "Alphabet Inc.", "Microsoft Corp", "Bajaj Holdings", "ITC Ltd"],
    sharpeRatio: 1.25,
  },
  {
    id: 2,
    name: "Axis Bluechip Fund",
    category: FundCategory.Equity,
    riskLevel: RiskLevel.High,
    returns: { '1yr': 25.1, '3yr': 12.5, '5yr': 15.2 },
    aum: 32612,
    expenseRatio: 0.98,
    fundManager: "Shreyash Devalkar",
    description: "A large-cap equity fund that aims to generate long-term capital appreciation by investing in a diversified portfolio predominantly consisting of equity and equity-related securities of large-cap companies.",
    topHoldings: ["ICICI Bank", "Infosys", "HDFC Bank", "Reliance Industries", "Bajaj Finance"],
    sharpeRatio: 0.98,
  },
  {
    id: 3,
    name: "SBI Small Cap Fund",
    category: FundCategory.Equity,
    riskLevel: RiskLevel.VeryHigh,
    returns: { '1yr': 20.5, '3yr': 27.2, '5yr': 25.1 },
    aum: 25524,
    expenseRatio: 0.71,
    fundManager: "R. Srinivasan",
    description: "A small-cap fund that seeks to provide investors with opportunities for long-term growth in capital from a portfolio of equity stocks of small-cap companies.",
    topHoldings: ["Blue Star Ltd", "Carborundum Universal", "Finolex Industries", "Triveni Turbine", "Elgi Equipments"],
    sharpeRatio: 1.35,
  },
  {
    id: 4,
    name: "HDFC Short Term Debt Fund",
    category: FundCategory.Debt,
    riskLevel: RiskLevel.Low,
    returns: { '1yr': 7.4, '3yr': 5.8, '5yr': 6.5 },
    aum: 13358,
    expenseRatio: 0.35,
    fundManager: "Anil Bamboli",
    description: "A debt fund that aims to generate regular income through investment in debt securities and money market instruments. It primarily invests in instruments with a Macaulay duration between 1 to 3 years.",
    topHoldings: ["Government of India Bonds", "NABARD", "Reliance Industries Ltd", "HDFC Bank Ltd", "Power Finance Corp"],
    sharpeRatio: 0.55,
  },
  {
    id: 5,
    name: "ICICI Prudential Balanced Advantage Fund",
    category: FundCategory.Hybrid,
    riskLevel: RiskLevel.High,
    returns: { '1yr': 22.8, '3yr': 14.1, '5yr': 15.9 },
    aum: 56334,
    expenseRatio: 1.05,
    fundManager: "Sankaran Naren",
    description: "A hybrid fund that dynamically manages its portfolio between equity and debt based on market valuations. It aims to provide capital appreciation and income distribution to the investors.",
    topHoldings: ["ICICI Bank", "HDFC Bank", "Infosys", "GOI Securities", "Reliance Industries"],
    sharpeRatio: 1.10,
  },
  {
    id: 6,
    name: "UTI Nifty 50 Index Fund",
    category: FundCategory.Index,
    riskLevel: RiskLevel.High,
    returns: { '1yr': 27.8, '3yr': 14.8, '5yr': 15.5 },
    aum: 16930,
    expenseRatio: 0.1,
    fundManager: "Sharwan Kumar Goyal",
    description: "An index fund that passively tracks the Nifty 50 index. It offers investors exposure to the top 50 companies in India at a very low cost.",
    topHoldings: ["Reliance Industries", "HDFC Bank", "ICICI Bank", "Infosys", "Larsen & Toubro"],
    sharpeRatio: 1.05,
  },
  {
    id: 7,
    name: "Tata Digital India Fund",
    category: FundCategory.Thematic,
    riskLevel: RiskLevel.VeryHigh,
    returns: { '1yr': 34.5, '3yr': 14.2, '5yr': 24.8 },
    aum: 9028,
    expenseRatio: 0.45,
    fundManager: "Meeta Shetty",
    description: "A thematic fund that invests in technology and technology-enabled companies in India. It aims to capture the growth potential of the digital revolution in the country.",
    topHoldings: ["Infosys", "Tata Consultancy Services", "Bharti Airtel", "Tech Mahindra", "Wipro"],
    sharpeRatio: 1.42,
  },
  {
    id: 8,
    name: "Mirae Asset Hybrid Equity Fund",
    category: FundCategory.Hybrid,
    riskLevel: RiskLevel.High,
    returns: { '1yr': 21.3, '3yr': 12.1, '5yr': 16.2 },
    aum: 8749,
    expenseRatio: 0.58,
    fundManager: "Harshad Borawake",
    description: "An aggressive hybrid fund which invests in a mix of equity and debt instruments to provide both capital appreciation and income.",
    topHoldings: ["HDFC Bank", "ICICI Bank", "Reliance Industries", "Infosys", "GOI Securities"],
    sharpeRatio: 1.15,
  },
];

export const EDUCATIONAL_TOPICS = [
    {
        title: "What are Mutual Funds?",
        prompt: "Explain what a mutual fund is in simple terms for a beginner investor. Cover the basic concepts like NAV, AMC, and how it pools money from investors. Keep it concise and easy to understand.",
    },
    {
        title: "Types of Mutual Funds",
        prompt: "Briefly explain the main types of mutual funds: Equity, Debt, and Hybrid funds. For each type, describe what it invests in and who it is suitable for.",
    },
    {
        title: "Understanding Risk",
        prompt: "Explain the common risks associated with mutual fund investing, such as market risk, interest rate risk, and credit risk. Use analogies to make it understandable for someone new to finance.",
    },
    {
        title: "SIP vs. Lumpsum",
        prompt: "Compare and contrast Systematic Investment Plan (SIP) and Lumpsum investing in mutual funds. List the pros and cons of each approach and suggest which type of investor might prefer each method.",
    }
];
